### ISSUE TITLE
Pixel art for pieces

### ISSUE THREAD

**Issue by cinegemadar** [cinegemadar/testris#2]
In the current implementation we have got a schematic head, toros, tail design. In the final product it should be changed to something more appealing.
- Each image should be 3x3 pixel
- Asymmetric under 90-degree rotation (so 4 90deg rotation needed to get the original state)
![torso](https://github.com/user-attachments/assets/ef91f18a-0146-437a-8098-f934a3fa8d5e)
![head](https://github.com/user-attachments/assets/c09a3468-112a-4c76-b091-31c84d69edf6)
![leg](https://github.com/user-attachments/assets/e786413c-b656-45a5-b94e-9576b75c40ec)

**Comment by gkisida** [comment]
Is the 3x3 pixel design intentional?
It is hard to visualize leg, torso, head with a 3x3 image, especially if those have to be asymmetric.

Additionally if those 3x3 pixels pieces can be moved left/right by one pixel then I would expect that those 3x3 objects can be tightly joined (similar to the classis tetris), for example:
```
                                                                       O..
       O..                .O.                                          .OO
if a   .OO   falls on a   O.O    I would expect they join this way:    OO.
       O..                .O.                                          O.O
                                                                       .O.
```
(the resulted block is only 5 pixels high here)

What if we had high resolution pieces (e.g. 20x20) and one left/right move could mean a full width of the piece?

**Comment by cinegemadar** [comment]
If you have the time to refactor, I have nothing against high res sprites. Although, we are rotating around the centre point (when pressing space) so an odd size length would make sense to have a centre point
